# Generated by Django 2.1.9 on 2019-06-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scripts_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('script_id', models.IntegerField(default=0)),
                ('script_name', models.CharField(default='', max_length=100)),
                ('script_type', models.IntegerField(default=0)),
                ('script_env', models.CharField(default='', max_length=50)),
                ('script_desc', models.CharField(default='', max_length=300)),
                ('create_time', models.DateTimeField(default='2012-12-12 12:12:12')),
                ('update_time', models.DateTimeField(default='2012-12-12 12:12:12')),
            ],
        ),
        migrations.DeleteModel(
            name='scripts',
        ),
    ]
