# Generated by Django 2.1.9 on 2019-06-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts_manage', '0002_auto_20190615_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts_info',
            name='script_env',
            field=models.IntegerField(default=''),
        ),
    ]
